---
- name: Find all object files
  find:
    paths: "{{ k8s_resource_dirs | join(',') }}"
    patterns: '*.yml,*.yaml'
    recurse: no
  register: oc_templates

- name: set k8s_resources with found files
  set_fact:
    k8s_resources: "{{ k8s_resources }} + [ '{{ item.path }}' ]"
  with_items: "{{ oc_templates.files }}"

- name: set k8s_resources with set files
  set_fact:
    k8s_resources: "{{ k8s_resources + [ item ] | k8s_filter }}"
  with_items: "{{ k8s_resource_files }}"

- name: set k8s_resource secrets with set files
  set_fact:
    k8s_secret_resources: "{{ k8s_resources + [ item ] | k8s_secrets_filter }}"
  with_items: "{{ k8s_resource_files }}"

