---
- name: Find all object files
  find:
    paths: "{{ k8s_resource_dirs | join(',') }}"
    patterns: '*.yml,*.yaml'
    recurse: no
  register: oc_templates

- name: set k8s_resources with found files
  set_fact:
    k8s_resource_files: "{{ k8s_resource_files + [ item.path ] }}"
  with_items: "{{ oc_templates.files }}"

- name: set k8s_resources with set files
  set_fact:
    k8s_resources: "{{  k8s_resource_files | k8s_filter }}"
