---
- name: Find all object files
  find:
    paths: "{{ k8s_resource_dirs | join(',') }}"
    patterns: '*.yml,*.yaml'
    recurse: no
  register: oc_templates

- name: set k8s_resources with found files
  set_fact:
    k8s_res_files: "{{ k8s_resource_files + oc_templates.files | map(attribute='path') | list }}"

- name: resource files to be applied
  debug:
    msg: "{{ k8s_res_files }}"

- name: set k8s_resources with set files
  set_fact:
    k8s_resources: "{{  k8s_res_files | k8s_filter }}"
